# Workflow suggested by ChatGPT
on:
  push:
    branches: [main, master]

name: pkgdown

jobs:
  pkgdown:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: r-lib/actions/setup-r@v2
      - uses: r-lib/actions/pkgdown@v3
